name: tetris
channels:
  - defaults
dependencies:
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - click=7.0
  - flask=1.1.1
  - itsdangerous=1.1.0
  - jinja2=2.10.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - markupsafe=1.1.1
  - ncurses=6.1
  - openssl=1.1.1c
  - pip=19.1.1
  - python=3.7.3
  - readline=7.0
  - setuptools=41.0.1
  - sqlite=3.29.0
  - tk=8.6.8
  - werkzeug=0.15.4
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - aniso8601==7.0.0
    - flask-restful==0.3.7
    - powerline-status==2.7
    - pytz==2019.1
    - six==1.12.0
    - flask_socketio
    - flask_ngrok

